"""Create Wikipedia edits table

Revision ID: 05d4bb77085d
Revises: 
Create Date: 2026-09-01 09:42:33.942627

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '05d4bb77085d'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('wikipedia_edits',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=500), nullable=False),
    sa.Column('user', sa.String(length=255), nullable=True),
    sa.Column('wiki', sa.String(length=100), nullable=True),
    sa.Column('change_type', sa.String(length=50), nullable=True),
    sa.Column('bot', sa.Boolean(), nullable=True),
    sa.Column('event_time', sa.DateTime(), nullable=True),
    sa.Column('collected_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('wikipedia_edits')
    # ### end Alembic commands ###
